workflows:
  android-workflow:
    name: Android Debug Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.example.packetcapture"
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk 